builds:
  - binary: grpcurl
    main: ./cmd/grpcurl
    goos:
      - linux
    goarch:
      - arm64
      - arm
    ldflags:
      - -s -w -X main.version=v{{.Version}}

archives:
  - format: tar.gz
    replacements:
      amd64: x86_64
      386: x86_32
    files:
      - LICENSE
